### ISSUE TITLE
Include libevdev on Android

### ISSUE THREAD

**Issue by AhmedX6** [openstf/minitouch#6]
Hello,

I created a jni project in Android with some C code to move cursor on screen and for injecting keyboard events.

I want to include livevdev for this following function : 
`unsigned int event_type = EV_KEY;
const char* name = "BTN_A";
int code = libevdev_event_code_from_name(event_type, name);
if(code < 0)
{
  puts("There was an error!");
}`

I need to handle the code of a keyboard key.
Please I'm lost on your documentation. I don't understand how to include libevdev on my jni folder.

Can you help me ?
It would be very nice

Thank you !

**Comment by sorccu** [comment]
No I can't really help you with that since it's for your own project and your question isn't specific enough. Asking for general guidance with your own project is more like consultation level work. Perhaps you could try asking the libevdev guys?

Note that not all devices expose keyboard events, so your code may not work on all devices anyway.
